#	$NetBSD: Makefile,v 1.21 2003/12/26 17:59:13 christos Exp $
#	@(#)Makefile	8.3 (Berkeley) 7/24/94

# Missing: ching dungeon warp
# Moved: chess
# Don't belong: xneko xroach

SUBDIR=	hunt

.include <bsd.subdir.mk>
